# The URL the site will be built for
author = "spiperac"
base_url = "https://spiperac.dev"
default_language = "en"

# Title
title = "spiperac's blog"
compile_sass = true
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml"]
generate_sitemap = true

taxonomies = [
    # You can enable/disable RSS
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "material-dark"
bottom_footnotes = true
external_links_target_blank = true

[extra]
codeblock = true
author = "spiperac"
github = "spiperac"
email = "spiperac@denkei.org"


