# The URL the site will be built for
author = "spiperac"
base_url = "https://spiperac.dev"
#theme = "apollo"
default_language = "en"

# Title
title = "spiperac's blog"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml"]
generate_sitemap = true

taxonomies = [
    # You can enable/disable RSS
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "material-dark"
bottom_footnotes = true
external_links_target_blank = true

[extra]
# Put all your custom variables here
codeblock = true
author = "spiperac"
github = "spiperac"
email = "spiperac@denkei.org"


